-- 011_auth_monitoring.sql
-- Tables for tracking authentication events and security alerts

-- Table for logging all authentication-related attempts and events
CREATE TABLE IF NOT EXISTS public.auth_events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    public_key TEXT,                   -- Stellar public key (actor)
    event_type VARCHAR(50) NOT NULL,   -- LOGIN_ATTEMPT, LOGIN_SUCCESS, LOGIN_FAILURE, LOGOUT, CHALLENGE_GENERATED
    status VARCHAR(20) NOT NULL,       -- SUCCESS, FAILURE
    failure_reason TEXT,               -- Reason for failure if status is FAILURE
    ip_address VARCHAR(45),            -- IPv4 or IPv6 address
    user_agent TEXT,                   -- Browser/Client information
    device_fingerprint TEXT,           -- Basic device identifier (optional)
    metadata JSONB DEFAULT '{}'::jsonb, -- Additional context (location, etc.)
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Table for security alerts generated by pattern detection
CREATE TABLE IF NOT EXISTS public.security_alerts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    public_key TEXT,                   -- The actor associated with the alert
    alert_type VARCHAR(50) NOT NULL,   -- BRUTE_FORCE, IMPOSSIBLE_TRAVEL, NEW_DEVICE, SUSPICIOUS_IP
    severity VARCHAR(20) NOT NULL,     -- LOW, MEDIUM, HIGH, CRITICAL
    description TEXT NOT NULL,         -- Human-readable description
    metadata JSONB DEFAULT '{}'::jsonb, -- Contextual data for investigation
    is_resolved BOOLEAN DEFAULT FALSE,  
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enable RLS (though mostly handled via service_role in backend)
ALTER TABLE public.auth_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.security_alerts ENABLE ROW LEVEL SECURITY;

-- Only admins can view auth events and alerts
CREATE POLICY "Admins can view auth events"
    ON public.auth_events
    FOR SELECT
    USING (
        (auth.jwt() ->> 'email' IN (SELECT email FROM auth.users WHERE raw_user_meta_data->>'is_admin' = 'true'))
    );

CREATE POLICY "Admins can view security alerts"
    ON public.security_alerts
    FOR SELECT
    USING (
        (auth.jwt() ->> 'email' IN (SELECT email FROM auth.users WHERE raw_user_meta_data->>'is_admin' = 'true'))
    );

-- Indexes for efficient monitoring and threat detection
CREATE INDEX IF NOT EXISTS idx_auth_events_public_key ON public.auth_events(public_key);
CREATE INDEX IF NOT EXISTS idx_auth_events_ip_address ON public.auth_events(ip_address);
CREATE INDEX IF NOT EXISTS idx_auth_events_event_type ON public.auth_events(event_type);
CREATE INDEX IF NOT EXISTS idx_auth_events_created_at ON public.auth_events(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_security_alerts_public_key ON public.security_alerts(public_key);
CREATE INDEX IF NOT EXISTS idx_security_alerts_alert_type ON public.security_alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_security_alerts_created_at ON public.security_alerts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_alerts_is_resolved ON public.security_alerts(is_resolved) WHERE is_resolved = FALSE;
